# Generated by Django 4.2.3 on 2023-07-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table_user',
            table='table_user',
        ),
    ]
