# Generated by Django 4.2.3 on 2023-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_table_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_user',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
